/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Ana
 */
public class FrmEditor extends javax.swing.JFrame {

    /**
     * Creates new form FrmEditor
     */
    public FrmEditor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcrArchivos = new javax.swing.JFileChooser();
        lblFuente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaBloc = new javax.swing.JTextArea();
        mbBloc = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        miNuevo = new javax.swing.JMenuItem();
        miAbrir = new javax.swing.JMenuItem();
        miGuardar = new javax.swing.JMenuItem();
        mFormato = new javax.swing.JMenu();
        miMayusculas = new javax.swing.JMenuItem();
        miMinusculas = new javax.swing.JMenuItem();
        miNegrita = new javax.swing.JMenuItem();
        miNormal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bloc de notas chido :u");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFuente.setFont(new java.awt.Font("Dialog", 0, 3)); // NOI18N
        lblFuente.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 282, 122, 30));

        txtaBloc.setColumns(20);
        txtaBloc.setRows(5);
        jScrollPane1.setViewportView(txtaBloc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 590));

        mArchivo.setText("Archivo");

        miNuevo.setText("Nuevo");
        mArchivo.add(miNuevo);

        miAbrir.setText("Abrir");
        mArchivo.add(miAbrir);

        miGuardar.setText("Guardar");
        mArchivo.add(miGuardar);

        mbBloc.add(mArchivo);

        mFormato.setText("Formato");

        miMayusculas.setText("Mayúsculas");
        miMayusculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMayusculasActionPerformed(evt);
            }
        });
        mFormato.add(miMayusculas);

        miMinusculas.setText("Minúsculas");
        mFormato.add(miMinusculas);

        miNegrita.setText("Negrita");
        miNegrita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNegritaActionPerformed(evt);
            }
        });
        mFormato.add(miNegrita);

        miNormal.setText("Normal");
        mFormato.add(miNormal);

        mbBloc.add(mFormato);

        setJMenuBar(mbBloc);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNegritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNegritaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miNegritaActionPerformed

    private void miMayusculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMayusculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miMayusculasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JFileChooser fcrArchivos;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblFuente;
    private javax.swing.JMenu mArchivo;
    public javax.swing.JMenu mFormato;
    private javax.swing.JMenuBar mbBloc;
    public javax.swing.JMenuItem miAbrir;
    public javax.swing.JMenuItem miGuardar;
    public javax.swing.JMenuItem miMayusculas;
    public javax.swing.JMenuItem miMinusculas;
    public javax.swing.JMenuItem miNegrita;
    public javax.swing.JMenuItem miNormal;
    public javax.swing.JMenuItem miNuevo;
    public javax.swing.JTextArea txtaBloc;
    // End of variables declaration//GEN-END:variables
}
